# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "address_ranges", :force => true do |t|
    t.column "tlid",     :integer,               :default => 0,   :null => false
    t.column "range_id", :integer,               :default => 0,   :null => false
    t.column "first",    :string,  :limit => 11, :default => "0", :null => false
    t.column "last",     :string,  :limit => 11, :default => "0", :null => false
  end

  add_index "address_ranges", ["tlid"], :name => "index_address_ranges_on_tlid"

  create_table "capital_cities", :force => true do |t|
    t.column "country", :string, :default => "",  :null => false
    t.column "capital", :string, :default => "",  :null => false
    t.column "lat",     :float,  :default => 0.0
    t.column "lng",     :float,  :default => 0.0
  end

  create_table "complete_chains", :force => true do |t|
    t.column "tlid",      :integer,                                 :default => 0, :null => false
    t.column "seq",       :integer,                                 :default => 0, :null => false
    t.column "latitude",  :decimal, :precision => 15, :scale => 10
    t.column "longitude", :decimal, :precision => 15, :scale => 10
  end

  add_index "complete_chains", ["tlid"], :name => "index_complete_chains_on_tlid"

  create_table "fcc_locations", :force => true do |t|
    t.column "unique_si", :integer
    t.column "lat_deg",   :integer
    t.column "lat_min",   :integer
    t.column "lat_sec",   :float
    t.column "lat_dir",   :string,  :limit => 1
    t.column "latitude",  :float
    t.column "long_deg",  :integer
    t.column "long_min",  :integer
    t.column "long_sec",  :float
    t.column "long_dir",  :string,  :limit => 1
    t.column "longitude", :float
  end

  add_index "fcc_locations", ["unique_si"], :name => "fcc_locations_unique_si_index"

  create_table "fcc_owners", :force => true do |t|
    t.column "unique_si", :integer
    t.column "name",      :string,  :limit => 200
    t.column "address",   :string,  :limit => 35
    t.column "city",      :string,  :limit => 20
    t.column "state",     :string,  :limit => 2
    t.column "zip",       :string,  :limit => 10
  end

  add_index "fcc_owners", ["unique_si"], :name => "fcc_owners_unique_si_index"

  create_table "fcc_structures", :force => true do |t|
    t.column "unique_si",        :integer
    t.column "date_constructed", :date
    t.column "date_dismantled",  :date
    t.column "address",          :string,  :limit => 80
    t.column "city",             :string,  :limit => 20
    t.column "state",            :string,  :limit => 2
    t.column "height",           :float
    t.column "elevation",        :float
    t.column "ohag",             :float
    t.column "ohamsl",           :float
    t.column "structure_type",   :string,  :limit => 6
  end

  add_index "fcc_structures", ["unique_si"], :name => "fcc_structures_unique_si_index"

  create_table "markers", :force => true do |t|
    t.column "lat",   :decimal,                :precision => 15, :scale => 10
    t.column "lng",   :decimal,                :precision => 15, :scale => 10
    t.column "found", :string,  :limit => 100
    t.column "left",  :string,  :limit => 100
    t.column "icon",  :string,  :limit => 100,                                 :default => ""
  end

  create_table "places", :force => true do |t|
    t.column "state_fips",  :string, :limit => 2,  :default => "", :null => false
    t.column "county_fips", :string, :limit => 3,  :default => "", :null => false
    t.column "place_fips",  :string, :limit => 5,  :default => "", :null => false
    t.column "state_name",  :string, :limit => 60, :default => "", :null => false
    t.column "county_name", :string, :limit => 30, :default => "", :null => false
    t.column "place_name",  :string, :limit => 30, :default => "", :null => false
  end

  create_table "stores", :force => true do |t|
    t.column "name",     :string, :limit => 50
    t.column "address",  :string, :limit => 100
    t.column "address2", :string, :limit => 100
    t.column "city",     :string, :limit => 50
    t.column "state",    :string, :limit => 2
    t.column "zip",      :string, :limit => 9
    t.column "phone",    :string, :limit => 15
    t.column "lat",      :string, :limit => 20
    t.column "lng",      :string, :limit => 20
  end

  create_table "street_names", :force => true do |t|
    t.column "tlid",        :integer,               :default => 0,  :null => false
    t.column "place_id",    :string,  :limit => 15, :default => "", :null => false
    t.column "cfcc",        :string,  :limit => 3,  :default => "", :null => false
    t.column "dir_prefix",  :string,  :limit => 2,  :default => "", :null => false
    t.column "name",        :string,  :limit => 30, :default => "", :null => false
    t.column "street_type", :string,  :limit => 4,  :default => "", :null => false
    t.column "dir_suffix",  :string,  :limit => 2,  :default => "", :null => false
  end

  add_index "street_names", ["tlid", "name"], :name => "index_street_names_on_tlid_and_name"

  create_table "towers", :force => true do |t|
    t.column "latitude",       :float
    t.column "longitude",      :float
    t.column "owner_name",     :string, :limit => 200
    t.column "owner_address",  :string, :limit => 35
    t.column "owner_city",     :string, :limit => 20
    t.column "owner_state",    :string, :limit => 2
    t.column "owner_zip",      :string, :limit => 10
    t.column "address",        :string, :limit => 80
    t.column "city",           :string, :limit => 20
    t.column "state",          :string, :limit => 2
    t.column "height",         :float
    t.column "elevation",      :float
    t.column "ohag",           :float
    t.column "ohamsl",         :float
    t.column "structure_type", :string, :limit => 6
  end

  add_index "towers", ["state"], :name => "towers_state_index"
  add_index "towers", ["latitude"], :name => "towers_latitude_index"
  add_index "towers", ["longitude"], :name => "towers_longitude_index"
  add_index "towers", ["latitude", "longitude"], :name => "towers_lat_ling_index"

  create_table "uk_postcodes", :force => true do |t|
    t.column "outcode",   :string, :limit => 4, :default => "",  :null => false
    t.column "latitude",  :float,               :default => 0.0, :null => false
    t.column "longitude", :float,               :default => 0.0, :null => false
  end

end
